### ISSUE TITLE
Array diff bug

### ISSUE THREAD

**Issue by yhack** [stefankoegl/python-json-patch#30]
Great program, but I think I found a bug. These steps will reproduce it:

src = [1,2,3] 
des = [3,1,4,2] 
Create a patch from these then apply the patch to src. It will produce an index out of bounds exception.

**Comment by domdom** [comment]
So this is still an issue, and I think it's all about how _optimize combines operations like remove and add as replace and move operations.
```{'op' : 'remove', 'path' : '/0', 'value' : 'some matched value'}```
``` ... ```
```{'op' : 'add', 'path' : '/1', 'value' : 'some matched value'}```
At first it may seem logical to replace these two commands with a single move command, but in order to do that properly you have to consider all the commands that alter the state of this array in between.

Let's say you replace the first command with a 'move' and delete the add:
```{'op' : 'move', 'from' : '/0', 'path' : '/1'}```
``` ... ```
``` <deleted> ```
But that path '/1' could actually be wrong. Any add or remove operations that take place between these two will alter what the correct location is supposed to be at the time of the move.

**Comment by apinkney97** [comment]
@domdom is correct: any operation that potentially changes the indexes of a range of elements (ie `add`, `remove`, `move`, `copy`) needs to be treated with caution when optimising.

I think the only "trivial" optimisation is a `remove` directly followed by an `add` to the same path, which can be substituted for a `move`.

**Comment by apinkney97** [comment]
Incidentally, this is the patch that gets produced for ``[1, 2, 3] -> [3, 1, 4, 2]`` if you don't call `_optimize` on it:
```
                                              [1, 2, 3]
{"op": "remove", "path": "/1", "value": 2}    [1, 3]
{"op": "remove", "path": "/0", "value": 2}    [3]
{"op": "add", "path": "/1", "value": 1}       [3, 1]
{"op": "add", "path": "/2", "value": 4}       [3, 1, 4]
{"op": "add", "path": "/3", "value": 2}       [3, 1, 4, 2]
```
do we know why the second ``remove`` has ``"value": 2``? Shouldn't it be 1?


My hand-made json patch for this change would be
```
                                              [1, 2, 3]
{"op": "move", "from": "/2", "path": "/0"}    [3, 1, 2]
{"op": "add", "path": "/2", "value": 4}       [3, 1, 4, 2]
```
which I arrived at by noticing that 1 and 2 are in the same order in the resultant list. I don't know how I'd put that down programatically (least of all in a nice generic way that would work in all cases).

**Comment by stefankoegl** [comment]
This issue seems to be fixed at least in current `master`, when looking at the example posted above.

````
>>> import jsonpatch
>>> a = ['23232812', '23232808', '23232807', '23232809', '23232811', '23232805', '23232810', '23232814', '23232806', '23232813']
>>> b = ['23232805', '23232806', '23232807', '23232808', '23232809', '23232810', '23232811', '23232812', '23232813', '23232814']
>>> jsonpatch.make_patch(a, b).apply(a) == b
True
````
